import {library} from "@fortawesome/fontawesome-svg-core";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";
import {
    faBan,
    faUserFriends,
    faSignInAlt,
    faSignOutAlt,
    faUserGear,
    faMessage,
    faUserPlus,
    faTrash,
    faAngleRight,
    faAngleLeft,
    faPenToSquare,
    faPen,
    faUserSecret,
    faLockOpen,
    faUserLock,
    faCheck,
    faArrowLeft,
    faPaperPlane,
} from "@fortawesome/free-solid-svg-icons";

library.add(faBan,
    faUserFriends,
    faSignInAlt,
    faSignOutAlt,
    faSignOutAlt,
    faUserGear,
    faMessage,
    faUserPlus,
    faTrash,
    faAngleRight,
    faAngleLeft,
    faPenToSquare,
    faPen,
    faUserSecret,
    faLockOpen,
    faUserLock,
    faCheck,
    faArrowLeft,
    faPaperPlane);
export {FontAwesomeIcon};